/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type BookLocationRequest = {
  /**
   * @format date-time
   */
  startDate: string;
  /**
   * @format date-time
   */
  endDate: string;
};

export type CreateLocationRequest = {
  name: string;
  address: string;
  description: string;
  /**
   * @format int32
   */
  capacity: number;
  /**
   * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
   */
  openTime: string;
  /**
   * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
   */
  closeTime: string;
  locationType: LocationType;
  images?: string[];
};

export type LocationDto = {
  /**
   * @format uuid
   */
  id?: string;
  name?: string;
  address?: string;
  description?: string;
  /**
   * @format int32
   */
  capacity?: number;
  /**
   * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
   */
  openTime?: string;
  /**
   * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
   */
  closeTime?: string;
  isActive?: boolean;
  locationType?: LocationType;
  images?: string[];
};

export enum LocationType {
  None = 0,
  Hotel = 1,
  BAndB = 2,
}

export type NullableOfLocationType = number;
