/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */

export enum LocationType {
  None = 0,
  Hotel = 1,
  BAndB = 2,
}

export type LocationDto = {
  /**
   * @format uuid
   */
  id?: string;
  name?: string;
  address?: string;
  description?: string;
  /**
   * @format int32
   */
  capacity?: number;
  /**
   * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
   */
  openTime?: string;
  /**
   * @pattern ^-?(\d+\.)?\d{2}:\d{2}:\d{2}(\.\d{1,7})?$
   */
  closeTime?: string;
  isActive?: boolean;
  locationType?: LocationType;
};
