name: Backend Tests & Coverage

on:
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: ./backend
        run: dotnet restore

      - name: Build solution
        working-directory: ./backend
        run: dotnet build --no-restore --configuration Release

      - name: Run tests with coverage
        working-directory: ./backend
        run: |
          dotnet test \
            --no-build \
            --configuration Release \
            --verbosity normal \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults \
            --logger "trx;LogFileName=test-results.trx" \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
        with:
          reports: 'backend/TestResults/**/coverage.opencover.xml'
          targetdir: 'backend/CoverageReport'
          reporttypes: 'HtmlInline;Cobertura;MarkdownSummaryGithub'
          sourcedirs: 'backend'
          title: 'Backend Code Coverage'

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: backend/CoverageReport/
          retention-days: 30

      - name: Upload test results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/TestResults/
          retention-days: 30

      - name: Add coverage summary to PR
        if: github.event_name == 'pull_request'
        run: |
          if [ -f backend/CoverageReport/SummaryGithub.md ]; then
            cat backend/CoverageReport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
          fi

      - name: Calculate branch coverage
        id: coverage
        if: github.event_name == 'pull_request'
        run: |
          python3 << 'EOF'
          import xml.etree.ElementTree as ET
          import glob
          import os

          # Parse coverage report
          coverage_files = glob.glob('backend/TestResults/*/coverage.opencover.xml')

          if not coverage_files:
              print("0")
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write("line_coverage=0\n")
                  f.write("covered_lines=0\n")
                  f.write("total_lines=0\n")
              exit(0)

          tree = ET.parse(coverage_files[0])
          root = tree.getroot()

          # Get overall line coverage from Summary element
          summary = root.find('.//Summary')
          if summary is not None:
              line_coverage = float(summary.get('sequenceCoverage', '0'))

              # Get total and covered lines
              visited = int(summary.get('visitedSequencePoints', '0'))
              total = int(summary.get('numSequencePoints', '0'))

              print(f"{line_coverage}")
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write(f"line_coverage={line_coverage}\n")
                  f.write(f"covered_lines={visited}\n")
                  f.write(f"total_lines={total}\n")
          else:
              print("0")
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write("line_coverage=0\n")
                  f.write("covered_lines=0\n")
                  f.write("total_lines=0\n")
          EOF

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');

            let coverageSummary = '';
            const summaryPath = 'backend/CoverageReport/SummaryGithub.md';

            if (fs.existsSync(summaryPath)) {
              coverageSummary = fs.readFileSync(summaryPath, 'utf8');

              // Remove only the Summary section (including its table)
              // Keep everything else including module/project coverage tables
              coverageSummary = coverageSummary.replace(/^#+ Summary.*$[\s\S]*?(?=^## )/m, '');

              // Clean up multiple consecutive blank lines
              coverageSummary = coverageSummary.replace(/\n{3,}/g, '\n\n');

              // Remove any leading blank lines
              coverageSummary = coverageSummary.replace(/^\s+/, '');

              // Clean up any trailing whitespace
              coverageSummary = coverageSummary.trim();
            }

            const lineCoverage = '${{ steps.coverage.outputs.line_coverage }}';
            const coveredLines = '${{ steps.coverage.outputs.covered_lines }}';
            const totalLines = '${{ steps.coverage.outputs.total_lines }}';
            const coveragePercent = parseFloat(lineCoverage);

            // Use checkmark for passing (>=90%), red X for failing
            let coverageIcon = '❌';
            if (coveragePercent >= 90) {
              coverageIcon = '✅';
            }

            const body = `${coverageIcon} **${lineCoverage}%** lines covered (${coveredLines}/${totalLines})

            ${coverageSummary}
            `;

            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment =>
              comment.user.type === 'Bot' &&
              comment.body.includes('lines covered')
            );

            if (botComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }

      - name: Check coverage threshold
        if: github.event_name == 'pull_request'
        run: |
          COVERAGE="${{ steps.coverage.outputs.line_coverage }}"
          THRESHOLD=90

          echo "Line Coverage: $COVERAGE%"
          echo "Threshold: $THRESHOLD%"

          if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
            echo "::warning::Line coverage ($COVERAGE%) is below the threshold ($THRESHOLD%)"
          else
            echo "::notice::Line coverage ($COVERAGE%) meets the threshold ($THRESHOLD%)"
          fi
