name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'e2e/**'
      - '.github/workflows/e2e-tests.yml'

jobs:
  e2e-tests:
    name: Run E2E Tests on PR Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install e2e dependencies
        working-directory: ./e2e
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        working-directory: ./e2e
        run: pnpm exec playwright install --with-deps chromium

      - name: Wait for PR deployment
        id: wait-deployment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Waiting for PR deployment to complete..."

          # Wait up to 10 minutes for deployment workflow to complete
          timeout 600 bash -c '
            while true; do
              # Get the latest deployment workflow run for this PR
              WORKFLOW_STATUS=$(gh run list \
                --workflow="pr-deploy.yml" \
                --json status,conclusion,headBranch \
                --jq "map(select(.headBranch == \"${{ github.head_ref }}\")) | .[0] | .status + \",\" + (.conclusion // \"\")")

              echo "Deployment status: $WORKFLOW_STATUS"

              STATUS=$(echo "$WORKFLOW_STATUS" | cut -d"," -f1)
              CONCLUSION=$(echo "$WORKFLOW_STATUS" | cut -d"," -f2)

              if [ "$STATUS" = "completed" ]; then
                if [ "$CONCLUSION" = "success" ]; then
                  echo "Deployment completed successfully!"
                  break
                else
                  echo "Deployment failed with conclusion: $CONCLUSION"
                  exit 1
                fi
              fi

              echo "Waiting for deployment... (status: $STATUS)"
              sleep 15
            done
          ' || {
            echo "Timeout or error waiting for deployment"
            exit 1
          }

          # Construct PR URLs based on naming convention
          FRONTEND_URL="https://pbooking-frontend-pr-${PR_NUMBER}.lemonwater-1ae5d7b2.swedencentral.azurecontainerapps.io"
          BACKEND_URL="https://pbooking-backend-pr-${PR_NUMBER}.lemonwater-1ae5d7b2.swedencentral.azurecontainerapps.io"

          echo "frontend_url=$FRONTEND_URL" >> $GITHUB_OUTPUT
          echo "backend_url=$BACKEND_URL" >> $GITHUB_OUTPUT

      - name: Verify frontend is accessible
        env:
          FRONTEND_URL: ${{ steps.wait-deployment.outputs.frontend_url }}
        run: |
          echo "Verifying frontend at ${FRONTEND_URL}"
          # Use --insecure to skip certificate verification and -L to follow redirects
          # Just verify we get any HTTP response (200, 404, etc.)
          timeout 120 bash -c "until curl -ksL -o /dev/null -w '%{http_code}' ${FRONTEND_URL} | grep -q '[2345][0-9][0-9]'; do echo 'Waiting for frontend...'; sleep 5; done"
          echo "Frontend is accessible!"

      - name: Run Playwright tests
        working-directory: ./e2e
        env:
          BASE_URL: ${{ steps.wait-deployment.outputs.frontend_url }}
        run: pnpm exec playwright test --project=chromium

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-pr-${{ github.event.pull_request.number }}
          path: e2e/playwright-report/
          retention-days: 30

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-pr-${{ github.event.pull_request.number }}
          path: e2e/test-results/
          retention-days: 30

      - name: Comment test results on PR
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FRONTEND_URL: ${{ steps.wait-deployment.outputs.frontend_url }}
        run: |
          # Count test results from playwright report
          if [ -f e2e/test-results/junit.xml ]; then
            TESTS_TOTAL=$(grep -oP 'tests="\K[0-9]+' e2e/test-results/junit.xml || echo "0")
            TESTS_FAILED=$(grep -oP 'failures="\K[0-9]+' e2e/test-results/junit.xml || echo "0")
            TESTS_PASSED=$((TESTS_TOTAL - TESTS_FAILED))

            if [ "$TESTS_FAILED" = "0" ]; then
              STATUS="✅ E2E Tests Passed"
              EMOJI="🎉"
            else
              STATUS="❌ E2E Tests Failed"
              EMOJI="⚠️"
            fi

            gh pr comment ${{ github.event.pull_request.number }} --body "${EMOJI} **${STATUS}**

            **Test Results:**
            - ✅ Passed: ${TESTS_PASSED}
            - ❌ Failed: ${TESTS_FAILED}
            - 📊 Total: ${TESTS_TOTAL}

            **Environment:**
            - Frontend: ${FRONTEND_URL}

            [View detailed report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          else
            gh pr comment ${{ github.event.pull_request.number }} --body "⚠️ **E2E Tests Issue**

            Could not find test results.

            [View workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          fi
