name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  RESOURCE_GROUP: BookingSystem-PR

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deactivate frontend revision
        id: cleanup-frontend
        continue-on-error: true
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REVISION="pbooking-frontend--pr-${PR_NUMBER}"

          echo "Deactivating frontend revision: ${REVISION}"

          az containerapp revision deactivate \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name pbooking-frontend \
            --revision ${REVISION}

          echo "Frontend revision deactivated successfully"

      - name: Deactivate backend revision
        id: cleanup-backend
        continue-on-error: true
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REVISION="pbooking-backend--pr-${PR_NUMBER}"

          echo "Deactivating backend revision: ${REVISION}"

          az containerapp revision deactivate \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name pbooking-backend \
            --revision ${REVISION}

          echo "Backend revision deactivated successfully"

      - name: Deactivate database revision
        id: cleanup-database
        continue-on-error: true
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REVISION="pbooking-database--pr-${PR_NUMBER}"

          echo "Deactivating database revision: ${REVISION}"

          az containerapp revision deactivate \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name pbooking-database \
            --revision ${REVISION}

          echo "Database revision deactivated successfully"
          echo "⚠️  Note: Database data is isolated per revision with name: portfolio_booking_pr_${PR_NUMBER}"

      - name: Cleanup summary
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          echo "🧹 Cleanup completed for PR #${PR_NUMBER}"
          echo ""
          echo "Cleaned resources:"
          echo "  ✅ Frontend revision: pbooking-frontend--pr-${PR_NUMBER}"
          echo "  ✅ Backend revision: pbooking-backend--pr-${PR_NUMBER}"
          echo "  ✅ Database revision: pbooking-database--pr-${PR_NUMBER}"
