name: Production Deployment

on:
  push:
    branches: [main]

jobs:
  deploy-production:
    uses: ./.github/workflows/_template-deploy.yml
    permissions:
      contents: read
      packages: write
      id-token: write

    with:
      environment_type: 'production'
      resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
      deployment_suffix: ''
      image_tag: 'latest'
      pr_number: ''

    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      db_password: ${{ secrets.DB_PASSWORD }}
      user_principal_id: ${{ secrets.USER_PRINCIPAL_ID }}
