name: Update Container Images (Reusable)

on:
  workflow_call:
    inputs:
      environment_type:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      pr_number:
        required: false
        type: string
        default: ''
      backend_image:
        required: true
        type: string
      frontend_image:
        required: true
        type: string

    secrets:
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true

    outputs:
      frontend_url:
        description: 'Frontend URL'
        value: ${{ jobs.update.outputs.frontend-url }}
      backend_url:
        description: 'Backend URL'
        value: ${{ jobs.update.outputs.backend-url }}

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      frontend-url: ${{ steps.get-urls.outputs.frontend-url }}
      backend-url: ${{ steps.get-urls.outputs.backend-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Update backend container app
        id: update-backend
        run: |
          NAME_PREFIX="pbooking"
          REVISION_LABEL="pr-${{ inputs.pr_number }}"

          echo "Updating backend container app for label: ${REVISION_LABEL}"
          echo "Backend image: ${{ inputs.backend_image }}"

          # Update using revision copy - this creates a new revision but keeps the same label
          # First, get the latest revision for this label
          LATEST_REVISION=$(az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-backend \
            --query "[?label=='${REVISION_LABEL}'].name" -o tsv | head -n 1)

          if [ -n "$LATEST_REVISION" ]; then
            echo "Found existing revision with label ${REVISION_LABEL}: ${LATEST_REVISION}"
            # Copy the revision with updated image, keeping the same label
            az containerapp revision copy \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-backend \
              --from-revision ${LATEST_REVISION} \
              --image "${{ inputs.backend_image }}" \
              --revision-label "${REVISION_LABEL}"
          else
            echo "No existing revision found, creating new revision with label ${REVISION_LABEL}"
            # Create new revision with label
            az containerapp update \
              --name ${NAME_PREFIX}-backend \
              --resource-group ${{ inputs.resource_group }} \
              --image "${{ inputs.backend_image }}" \
              --set-env-vars "REVISION_LABEL=${REVISION_LABEL}"

            # Set label on the latest revision
            NEW_REVISION=$(az containerapp revision list \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-backend \
              --query "[0].name" -o tsv)

            az containerapp revision label add \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-backend \
              --revision ${NEW_REVISION} \
              --label "${REVISION_LABEL}"
          fi

          echo "Backend updated successfully with label ${REVISION_LABEL}"
          echo "revision-label=${REVISION_LABEL}" >> $GITHUB_OUTPUT

      - name: Update frontend container app
        id: update-frontend
        run: |
          NAME_PREFIX="pbooking"
          REVISION_LABEL="pr-${{ inputs.pr_number }}"

          echo "Updating frontend container app for label: ${REVISION_LABEL}"
          echo "Frontend image: ${{ inputs.frontend_image }}"

          # Update using revision copy - this creates a new revision but keeps the same label
          LATEST_REVISION=$(az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-frontend \
            --query "[?label=='${REVISION_LABEL}'].name" -o tsv | head -n 1)

          if [ -n "$LATEST_REVISION" ]; then
            echo "Found existing revision with label ${REVISION_LABEL}: ${LATEST_REVISION}"
            az containerapp revision copy \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-frontend \
              --from-revision ${LATEST_REVISION} \
              --image "${{ inputs.frontend_image }}" \
              --revision-label "${REVISION_LABEL}"
          else
            echo "No existing revision found, creating new revision with label ${REVISION_LABEL}"
            az containerapp update \
              --name ${NAME_PREFIX}-frontend \
              --resource-group ${{ inputs.resource_group }} \
              --image "${{ inputs.frontend_image }}"

            NEW_REVISION=$(az containerapp revision list \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-frontend \
              --query "[0].name" -o tsv)

            az containerapp revision label add \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-frontend \
              --revision ${NEW_REVISION} \
              --label "${REVISION_LABEL}"
          fi

          echo "Frontend updated successfully with label ${REVISION_LABEL}"

      - name: Get deployment URLs
        id: get-urls
        run: |
          NAME_PREFIX="pbooking"
          REVISION_LABEL="pr-${{ inputs.pr_number }}"

          if [ "${{ inputs.environment_type }}" == "preview" ]; then
            # For PR environments, use the label-based URL (stable across updates)
            # Label URL format: https://{app-name}---{label}.{region}.azurecontainerapps.io

            # Get container app location
            LOCATION=$(az containerapp show \
              --name ${NAME_PREFIX}-frontend \
              --resource-group ${{ inputs.resource_group }} \
              --query location -o tsv)

            # Construct label-based URLs (these stay the same even when revision changes)
            FRONTEND_URL="https://${NAME_PREFIX}-frontend---${REVISION_LABEL}.${LOCATION}.azurecontainerapps.io"
            BACKEND_URL="https://${NAME_PREFIX}-backend---${REVISION_LABEL}.${LOCATION}.azurecontainerapps.io"

            echo "Using label-based URLs (stable across updates):"
            echo "Frontend label URL: ${FRONTEND_URL}"
            echo "Backend label URL: ${BACKEND_URL}"
          else
            # For production, get the main FQDN
            FRONTEND_FQDN=$(az containerapp show \
              --name ${NAME_PREFIX}-frontend \
              --resource-group ${{ inputs.resource_group }} \
              --query properties.configuration.ingress.fqdn -o tsv)

            BACKEND_FQDN=$(az containerapp show \
              --name ${NAME_PREFIX}-backend \
              --resource-group ${{ inputs.resource_group }} \
              --query properties.configuration.ingress.fqdn -o tsv)

            FRONTEND_URL="https://${FRONTEND_FQDN}"
            BACKEND_URL="https://${BACKEND_FQDN}"
          fi

          echo "Frontend URL: ${FRONTEND_URL}"
          echo "Backend URL: ${BACKEND_URL}"

          echo "frontend-url=${FRONTEND_URL}" >> $GITHUB_OUTPUT
          echo "backend-url=${BACKEND_URL}" >> $GITHUB_OUTPUT
