name: Infrastructure Deployment (Reusable)

on:
  workflow_call:
    inputs:
      environment_type:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      pr_number:
        required: false
        type: string
        default: ''
      backend_image:
        required: true
        type: string
      frontend_image:
        required: true
        type: string

    secrets:
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      db_password:
        required: true

    outputs:
      frontend_url:
        description: 'Frontend URL'
        value: ${{ jobs.deploy.outputs.frontend-url }}
      backend_url:
        description: 'Backend URL'
        value: ${{ jobs.deploy.outputs.backend-url }}
      frontend_pr_url:
        description: 'Frontend PR labeled URL (preview only)'
        value: ${{ jobs.deploy.outputs.frontend-pr-url }}
      backend_pr_url:
        description: 'Backend PR labeled URL (preview only)'
        value: ${{ jobs.deploy.outputs.backend-pr-url }}
      deployment_name:
        description: 'Deployment name'
        value: ${{ jobs.deploy.outputs.deployment-name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      frontend-url: ${{ steps.get-urls.outputs.frontend-url }}
      backend-url: ${{ steps.get-urls.outputs.backend-url }}
      frontend-pr-url: ${{ steps.get-labeled-urls.outputs.frontend-pr-url || steps.get-urls.outputs.frontend-pr-url }}
      backend-pr-url: ${{ steps.get-labeled-urls.outputs.backend-pr-url || steps.get-urls.outputs.backend-pr-url }}
      deployment-name: ${{ steps.deploy.outputs.deployment-name }}
      deployment-hash: ${{ steps.deploy.outputs.deployment-hash }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Remove existing PR revisions
        if: inputs.environment_type == 'preview'
        continue-on-error: true
        run: |
          NAME_PREFIX="pbooking"
          REVISION_LABEL="pr-${{ inputs.pr_number }}"

          echo "Removing existing revisions with label '${REVISION_LABEL}' for PR ${{ inputs.pr_number }}"

          # Find and deactivate revisions with the PR label for frontend
          FRONTEND_LABELED_REVISIONS=$(az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-frontend \
            --query "[?properties.trafficWeight>0 && properties.fqdn!=null].{name:name,labels:properties.template.revisionSuffix}" \
            --output json 2>/dev/null || echo "[]")

          # Get revisions that have the PR label
          FRONTEND_REVISIONS_WITH_LABEL=$(az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-frontend \
            --query "[].name" -o tsv 2>/dev/null | while read revision; do
              if az containerapp revision show \
                --resource-group ${{ inputs.resource_group }} \
                --name ${NAME_PREFIX}-frontend \
                --revision "$revision" \
                --query "properties.labels.\"${REVISION_LABEL}\"" -o tsv 2>/dev/null | grep -q "^${REVISION_LABEL}$"; then
                echo "$revision"
              fi
            done)

          if [ -n "$FRONTEND_REVISIONS_WITH_LABEL" ]; then
            echo "Found frontend revisions with label '${REVISION_LABEL}': $FRONTEND_REVISIONS_WITH_LABEL"
            echo "$FRONTEND_REVISIONS_WITH_LABEL" | while read revision; do
              if [ -n "$revision" ]; then
                echo "Deactivating frontend revision: $revision"
                az containerapp revision deactivate \
                  --resource-group ${{ inputs.resource_group }} \
                  --name ${NAME_PREFIX}-frontend \
                  --revision "$revision" 2>/dev/null || echo "Failed to deactivate $revision"
              fi
            done
          else
            echo "No frontend revisions found with label '${REVISION_LABEL}'"
          fi

          # Find and deactivate revisions with the PR label for backend
          BACKEND_REVISIONS_WITH_LABEL=$(az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-backend \
            --query "[].name" -o tsv 2>/dev/null | while read revision; do
              if az containerapp revision show \
                --resource-group ${{ inputs.resource_group }} \
                --name ${NAME_PREFIX}-backend \
                --revision "$revision" \
                --query "properties.labels.\"${REVISION_LABEL}\"" -o tsv 2>/dev/null | grep -q "^${REVISION_LABEL}$"; then
                echo "$revision"
              fi
            done)

          if [ -n "$BACKEND_REVISIONS_WITH_LABEL" ]; then
            echo "Found backend revisions with label '${REVISION_LABEL}': $BACKEND_REVISIONS_WITH_LABEL"
            echo "$BACKEND_REVISIONS_WITH_LABEL" | while read revision; do
              if [ -n "$revision" ]; then
                echo "Deactivating backend revision: $revision"
                az containerapp revision deactivate \
                  --resource-group ${{ inputs.resource_group }} \
                  --name ${NAME_PREFIX}-backend \
                  --revision "$revision" 2>/dev/null || echo "Failed to deactivate $revision"
              fi
            done
          else
            echo "No backend revisions found with label '${REVISION_LABEL}'"
          fi

      - name: Deploy infrastructure
        id: deploy
        run: |
          TEMPLATE_FILE="infrastructure/azure-setup.bicep"

          # Generate deployment hash for all environments to ensure unique revisions
          DEPLOYMENT_HASH=$(date +%s | sha256sum | head -c 5)

          if [ "${{ inputs.environment_type }}" == "production" ]; then
            DEPLOYMENT_NAME="production-${DEPLOYMENT_HASH}"
          else
            DEPLOYMENT_NAME="pr-${{ inputs.pr_number }}-${DEPLOYMENT_HASH}"
          fi

          NAME_PREFIX="pbooking"

          echo "Deploying to ${{ inputs.resource_group }} as ${DEPLOYMENT_NAME}"
          echo "Backend: ${{ inputs.backend_image }}"
          echo "Frontend: ${{ inputs.frontend_image }}"
          echo "Deployment hash: ${DEPLOYMENT_HASH}"
          echo "deployment-name=${DEPLOYMENT_NAME}" >> $GITHUB_OUTPUT
          echo "deployment-hash=${DEPLOYMENT_HASH}" >> $GITHUB_OUTPUT

          # Execute the deployment with verbose logging
          set +e  # Don't exit on error, we want to capture it
          az deployment group create \
            --resource-group ${{ inputs.resource_group }} \
            --name ${DEPLOYMENT_NAME} \
            --template-file ${TEMPLATE_FILE} \
            --parameters namePrefix=${NAME_PREFIX} \
            --parameters location=swedencentral \
            --parameters environmentType=${{ inputs.environment_type }} \
            --parameters prNumber="${{ inputs.pr_number }}" \
            --parameters backendImage="${{ inputs.backend_image }}" \
            --parameters frontendImage="${{ inputs.frontend_image }}" \
            --parameters databasePassword="${{ secrets.db_password }}" \
            --parameters deploymentHash="${DEPLOYMENT_HASH}" \
            --verbose

          DEPLOYMENT_EXIT_CODE=$?

          if [ $DEPLOYMENT_EXIT_CODE -ne 0 ]; then
            echo "::error::Deployment failed with exit code $DEPLOYMENT_EXIT_CODE"

            echo "===== Deployment Error Details ====="
            az deployment operation group list \
              --resource-group ${{ inputs.resource_group }} \
              --name ${DEPLOYMENT_NAME} \
              --query "[?properties.provisioningState=='Failed'].{Operation: properties.targetResource.resourceName, Error: properties.statusMessage.error}" \
              --output json || true

            exit $DEPLOYMENT_EXIT_CODE
          fi

      - name: Get deployment URLs
        id: get-urls
        run: |
          DEPLOYMENT_NAME="${{ steps.deploy.outputs.deployment-name }}"

          # For all environments, get URLs from deployment outputs
          FRONTEND_URL=$(az deployment group show \
            --resource-group ${{ inputs.resource_group }} \
            --name ${DEPLOYMENT_NAME} \
            --query properties.outputs.frontendUrl.value -o tsv)

          BACKEND_URL=$(az deployment group show \
            --resource-group ${{ inputs.resource_group }} \
            --name ${DEPLOYMENT_NAME} \
            --query properties.outputs.backendUrl.value -o tsv)

          # Get PR-specific labeled URLs (only for preview environments)
          FRONTEND_PR_URL=$(az deployment group show \
            --resource-group ${{ inputs.resource_group }} \
            --name ${DEPLOYMENT_NAME} \
            --query properties.outputs.frontendPrUrl.value -o tsv 2>/dev/null || echo "")

          BACKEND_PR_URL=$(az deployment group show \
            --resource-group ${{ inputs.resource_group }} \
            --name ${DEPLOYMENT_NAME} \
            --query properties.outputs.backendPrUrl.value -o tsv 2>/dev/null || echo "")

          echo "Frontend: ${FRONTEND_URL}"
          echo "Backend: ${BACKEND_URL}"
          echo "Frontend PR: ${FRONTEND_PR_URL}"
          echo "Backend PR: ${BACKEND_PR_URL}"

          echo "frontend-url=${FRONTEND_URL}" >> $GITHUB_OUTPUT
          echo "backend-url=${BACKEND_URL}" >> $GITHUB_OUTPUT
          echo "frontend-pr-url=${FRONTEND_PR_URL}" >> $GITHUB_OUTPUT
          echo "backend-pr-url=${BACKEND_PR_URL}" >> $GITHUB_OUTPUT

      - name: Apply revision labels for PR environments
        if: inputs.environment_type == 'preview'
        run: |
          NAME_PREFIX="pbooking"
          REVISION_LABEL="pr-${{ inputs.pr_number }}"
          DEPLOYMENT_HASH="${{ steps.deploy.outputs.deployment-hash }}"

          echo "Applying revision labels for PR ${{ inputs.pr_number }}"
          echo "Looking for revisions with deployment hash: ${DEPLOYMENT_HASH}"

          # Debug: List all current revisions
          echo "=== All frontend revisions ==="
          az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-frontend \
            --query "[].{name:name,createdTime:properties.createdTime,active:properties.active}" -o table

          echo "=== All backend revisions ==="
          az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-backend \
            --query "[].{name:name,createdTime:properties.createdTime,active:properties.active}" -o table

          # Get the most recent active revision for frontend (simpler approach)
          FRONTEND_REVISION=$(az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-frontend \
            --query "[?properties.active] | sort_by(@, &properties.createdTime) | [-1].name" -o tsv)

          if [ -n "$FRONTEND_REVISION" ]; then
            echo "Applying label '${REVISION_LABEL}' to frontend revision: $FRONTEND_REVISION"
            az containerapp revision label add \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-frontend \
              --revision "$FRONTEND_REVISION" \
              --label "$REVISION_LABEL" \
              --verbose

            # Verify the label was applied
            echo "Verifying frontend label was applied:"
            az containerapp revision show \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-frontend \
              --revision "$FRONTEND_REVISION" \
              --query "properties.template.revisionLabel" -o tsv
          else
            echo "No active frontend revision found"
          fi

          # Get the most recent active revision for backend (simpler approach)
          BACKEND_REVISION=$(az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-backend \
            --query "[?properties.active] | sort_by(@, &properties.createdTime) | [-1].name" -o tsv)

          if [ -n "$BACKEND_REVISION" ]; then
            echo "Applying label '${REVISION_LABEL}' to backend revision: $BACKEND_REVISION"
            az containerapp revision label add \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-backend \
              --revision "$BACKEND_REVISION" \
              --label "$REVISION_LABEL" \
              --verbose

            # Verify the label was applied
            echo "Verifying backend label was applied:"
            az containerapp revision show \
              --resource-group ${{ inputs.resource_group }} \
              --name ${NAME_PREFIX}-backend \
              --revision "$BACKEND_REVISION" \
              --query "properties.template.revisionLabel" -o tsv
          else
            echo "No active backend revision found"
          fi

      - name: Get labeled URLs after applying labels
        if: inputs.environment_type == 'preview'
        id: get-labeled-urls
        run: |
          NAME_PREFIX="pbooking"
          REVISION_LABEL="pr-${{ inputs.pr_number }}"

          # Get the FQDN for each app
          FRONTEND_FQDN=$(az containerapp show \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-frontend \
            --query properties.configuration.ingress.fqdn -o tsv)

          BACKEND_FQDN=$(az containerapp show \
            --resource-group ${{ inputs.resource_group }} \
            --name ${NAME_PREFIX}-backend \
            --query properties.configuration.ingress.fqdn -o tsv)

          # Construct labeled URLs
          FRONTEND_LABELED_URL="https://${REVISION_LABEL}---${FRONTEND_FQDN}"
          BACKEND_LABELED_URL="https://${REVISION_LABEL}---${BACKEND_FQDN}"

          echo "Frontend labeled URL: ${FRONTEND_LABELED_URL}"
          echo "Backend labeled URL: ${BACKEND_LABELED_URL}"

          # Update the outputs with actual labeled URLs
          echo "frontend-pr-url=${FRONTEND_LABELED_URL}" >> $GITHUB_OUTPUT
          echo "backend-pr-url=${BACKEND_LABELED_URL}" >> $GITHUB_OUTPUT
