name: Infrastructure Deployment (Reusable)

on:
  workflow_call:
    inputs:
      environment_type:
        required: true
        type: string
      resource_group:
        required: true
        type: string
      pr_number:
        required: false
        type: string
        default: ''
      backend_image:
        required: true
        type: string
      frontend_image:
        required: true
        type: string

    secrets:
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      db_password:
        required: true
      managed_identity_id:
        required: true

    outputs:
      frontend_url:
        description: 'Frontend URL'
        value: ${{ jobs.deploy.outputs.frontend-url }}
      backend_url:
        description: 'Backend URL'
        value: ${{ jobs.deploy.outputs.backend-url }}
      deployment_name:
        description: 'Deployment name'
        value: ${{ jobs.deploy.outputs.deployment-name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      frontend-url: ${{ steps.get-urls.outputs.frontend-url }}
      backend-url: ${{ steps.get-urls.outputs.backend-url }}
      deployment-name: ${{ steps.deploy.outputs.deployment-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Delete existing PR revisions
        if: inputs.environment_type == 'preview'
        continue-on-error: true
        run: |
          REVISION_SUFFIX="pr-${{ inputs.pr_number }}"

          echo "Checking for existing revisions with suffix: ${REVISION_SUFFIX}"

          # Deactivate frontend revision if exists
          FRONTEND_REVISIONS=$(az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name pbooking-pr-frontend \
            --query "[?ends_with(name, '-${REVISION_SUFFIX}')].name" -o tsv)

          if [ -n "$FRONTEND_REVISIONS" ]; then
            echo "Deactivating frontend revisions: $FRONTEND_REVISIONS"
            echo "$FRONTEND_REVISIONS" | while read revision; do
              az containerapp revision deactivate \
                --resource-group ${{ inputs.resource_group }} \
                --name pbooking-pr-frontend \
                --revision "$revision"
            done
          else
            echo "No frontend revisions found"
          fi

          # Deactivate backend revision if exists
          BACKEND_REVISIONS=$(az containerapp revision list \
            --resource-group ${{ inputs.resource_group }} \
            --name pbooking-pr-backend \
            --query "[?ends_with(name, '-${REVISION_SUFFIX}')].name" -o tsv)

          if [ -n "$BACKEND_REVISIONS" ]; then
            echo "Deactivating backend revisions: $BACKEND_REVISIONS"
            echo "$BACKEND_REVISIONS" | while read revision; do
              az containerapp revision deactivate \
                --resource-group ${{ inputs.resource_group }} \
                --name pbooking-pr-backend \
                --revision "$revision"
            done
          else
            echo "No backend revisions found"
          fi

      - name: Deploy infrastructure
        id: deploy
        run: |
          TEMPLATE_FILE="infrastructure/azure-setup.bicep"

          if [ "${{ inputs.environment_type }}" == "production" ]; then
            DEPLOYMENT_HASH=$(date +%s | sha256sum | head -c 5)
            DEPLOYMENT_NAME="production-${DEPLOYMENT_HASH}"
            NAME_PREFIX="pbooking"
          else
            DEPLOYMENT_NAME="pr-${{ inputs.pr_number }}"
            DEPLOYMENT_HASH=""
            NAME_PREFIX="pbooking-pr"
          fi

          echo "Deploying to ${{ inputs.resource_group }} as ${DEPLOYMENT_NAME}"
          echo "Backend: ${{ inputs.backend_image }}"
          echo "Frontend: ${{ inputs.frontend_image }}"
          echo "deployment-name=${DEPLOYMENT_NAME}" >> $GITHUB_OUTPUT

          # Execute the deployment with verbose logging
          set +e  # Don't exit on error, we want to capture it
          az deployment group create \
            --resource-group ${{ inputs.resource_group }} \
            --name ${DEPLOYMENT_NAME} \
            --template-file ${TEMPLATE_FILE} \
            --parameters namePrefix=${NAME_PREFIX} \
            --parameters location=swedencentral \
            --parameters environmentType=${{ inputs.environment_type }} \
            --parameters prNumber="${{ inputs.pr_number }}" \
            --parameters backendImage="${{ inputs.backend_image }}" \
            --parameters frontendImage="${{ inputs.frontend_image }}" \
            --parameters databasePassword="${{ secrets.db_password }}" \
            --parameters deploymentHash="${DEPLOYMENT_HASH}" \
            --parameters managedIdentityId="${{ secrets.managed_identity_id }}" \
            --verbose

          DEPLOYMENT_EXIT_CODE=$?

          if [ $DEPLOYMENT_EXIT_CODE -ne 0 ]; then
            echo "::error::Deployment failed with exit code $DEPLOYMENT_EXIT_CODE"

            echo "===== Deployment Error Details ====="
            az deployment operation group list \
              --resource-group ${{ inputs.resource_group }} \
              --name ${DEPLOYMENT_NAME} \
              --query "[?properties.provisioningState=='Failed'].{Operation: properties.targetResource.resourceName, Error: properties.statusMessage.error}" \
              --output json || true

            echo "===== Full Deployment Status ====="
            az deployment group show \
              --resource-group ${{ inputs.resource_group }} \
              --name ${DEPLOYMENT_NAME} \
              --query "{Status: properties.provisioningState, Error: properties.error}" \
              --output json || true

            exit $DEPLOYMENT_EXIT_CODE
          fi

      - name: Get deployment URLs
        id: get-urls
        run: |
          DEPLOYMENT_NAME="${{ steps.deploy.outputs.deployment-name }}"

          if [ "${{ inputs.environment_type }}" == "preview" ]; then
            # For PR environments, get the specific revision URLs
            REVISION_SUFFIX="pr-${{ inputs.pr_number }}"

            # Get frontend revision URL
            FRONTEND_REVISION=$(az containerapp revision list \
              --resource-group ${{ inputs.resource_group }} \
              --name pbooking-pr-frontend \
              --query "[?ends_with(name, '-${REVISION_SUFFIX}')].name" -o tsv | head -n 1)

            FRONTEND_URL=$(az containerapp revision show \
              --resource-group ${{ inputs.resource_group }} \
              --name pbooking-pr-frontend \
              --revision ${FRONTEND_REVISION} \
              --query properties.fqdn -o tsv)

            # Get backend revision URL
            BACKEND_REVISION=$(az containerapp revision list \
              --resource-group ${{ inputs.resource_group }} \
              --name pbooking-pr-backend \
              --query "[?ends_with(name, '-${REVISION_SUFFIX}')].name" -o tsv | head -n 1)

            BACKEND_URL=$(az containerapp revision show \
              --resource-group ${{ inputs.resource_group }} \
              --name pbooking-pr-backend \
              --revision ${BACKEND_REVISION} \
              --query properties.fqdn -o tsv)

            # Add https:// prefix
            FRONTEND_URL="https://${FRONTEND_URL}"
            BACKEND_URL="https://${BACKEND_URL}"
          else
            # For production, get URLs from deployment outputs
            FRONTEND_URL=$(az deployment group show \
              --resource-group ${{ inputs.resource_group }} \
              --name ${DEPLOYMENT_NAME} \
              --query properties.outputs.frontendUrl.value -o tsv)

            BACKEND_URL=$(az deployment group show \
              --resource-group ${{ inputs.resource_group }} \
              --name ${DEPLOYMENT_NAME} \
              --query properties.outputs.backendUrl.value -o tsv)
          fi

          echo "Frontend: ${FRONTEND_URL}"
          echo "Backend: ${BACKEND_URL}"

          echo "frontend-url=${FRONTEND_URL}" >> $GITHUB_OUTPUT
          echo "backend-url=${BACKEND_URL}" >> $GITHUB_OUTPUT
