name: Deploy Template (Reusable)

on:
  workflow_call:
    inputs:
      environment_type:
        description: 'Deployment environment type'
        required: true
        type: string  # 'production' or 'preview'

      resource_group:
        description: 'Azure resource group name'
        required: true
        type: string  # 'BookingSystem' or 'BookingSystem-PR'

      deployment_suffix:
        description: 'Deployment suffix for multi-revision (empty for production)'
        required: false
        type: string
        default: ''  # Empty for prod, 'pr-123' for preview

      image_tag:
        description: 'Docker image tag to deploy'
        required: true
        type: string  # 'latest' or 'pr-123'

      pr_number:
        description: 'Pull request number (for preview deployments only)'
        required: false
        type: string
        default: ''

    secrets:
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      db_password:
        required: true

    outputs:
      frontend_pr_url:
        description: 'Frontend PR labeled URL (preview only)'
        value: ${{ jobs.deploy-infra.outputs.frontend_pr_url }}
      backend_pr_url:
        description: 'Backend PR labeled URL (preview only)'
        value: ${{ jobs.deploy-infra.outputs.backend_pr_url }}

jobs:
  # Phase 1: Build Docker images
  build-images:
    uses: ./.github/workflows/template-build-images.yml
    permissions:
      contents: read
      packages: write
    with:
      image_tag: ${{ inputs.image_tag }}

  # Phase 2: Deploy infrastructure with actual images
  deploy-infra:
    needs: build-images
    uses: ./.github/workflows/template-infra-deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment_type: ${{ inputs.environment_type }}
      resource_group: ${{ inputs.resource_group }}
      pr_number: ${{ inputs.pr_number }}
      backend_image: ${{ needs.build-images.outputs.backend_image }}
      frontend_image: ${{ needs.build-images.outputs.frontend_image }}
    secrets:
      azure_client_id: ${{ secrets.azure_client_id }}
      azure_tenant_id: ${{ secrets.azure_tenant_id }}
      azure_subscription_id: ${{ secrets.azure_subscription_id }}
      db_password: ${{ secrets.db_password }}
